import type { Metadata } from "next";
import { ArrowRight, Clock3, Quote } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { articles } from "@/lib/data";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return articles.map((article) => ({ slug: article.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = articles.find((item) => item.slug === slug); return article ? { title: article.title, description: article.excerpt } : {}; }
export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = articles.find((item) => item.slug === slug); if (!article) notFound(); return <div className="page-wrap"><article className="mx-auto mt-8 max-w-4xl"><Link href="/blog" className="mb-5 flex w-fit items-center gap-2 text-[10px] font-bold text-[var(--muted)]"><ArrowRight className="size-3" />بازگشت به مجله</Link><header className="rounded-[32px] bg-[var(--ink)] px-6 py-12 text-white sm:px-12 sm:py-16"><div className="flex items-center gap-3 text-[10px] text-[var(--acid)]"><span>{article.category}</span><span className="size-1 rounded-full bg-white/25" /><span className="flex items-center gap-1 text-white/45"><Clock3 className="size-3" />{article.readTime}</span></div><h1 className="mt-6 text-3xl font-black leading-[1.55] tracking-[-.05em] sm:text-5xl">{article.title}</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-white/50">{article.excerpt}</p></header><div className="px-2 py-10 text-sm leading-9 text-[var(--muted)] sm:px-10"><p>صدای خوب معمولاً نتیجه یک حرکت جادویی نیست؛ حاصل چند تصمیم کوچک است که در زمان درست گرفته می‌شوند. قبل از اینکه سراغ ابزار بعدی برویم، باید بفهمیم قطعه واقعاً چه چیزی کم دارد.</p><h2 className="mt-9 text-xl font-black text-[var(--foreground)]">اول گوش کن، بعد دست به ابزار ببر</h2><p className="mt-3">چند بار قطعه را بدون لمس هیچ کنترلری گوش کن. جاهایی که انرژی افت می‌کند، بخش‌هایی که شلوغ‌اند و لحظه‌هایی که توجهت از ملودی جدا می‌شود را یادداشت کن. همین نقشه ساده، مسیر تصمیم‌های بعدی را روشن می‌کند.</p><blockquote className="my-9 rounded-[24px] bg-[var(--acid)] p-6 text-lg font-black leading-9 text-[var(--ink)]"><Quote className="mb-4 size-6" />اگر هر صدا دلیلی برای حضور نداشته باشد، حذف‌کردنش معمولاً میکس را بهتر می‌کند.</blockquote><h2 className="text-xl font-black text-[var(--foreground)]">یک تغییر در هر مرحله</h2><p className="mt-3">وقتی هم‌زمان EQ، کمپرس و سچوریشن را عوض می‌کنی، دیگر نمی‌دانی کدام تصمیم نتیجه را بهتر کرده است. تغییرها را کوچک نگه دار و بعد از هر مرحله دوباره با نسخه قبلی مقایسه کن.</p><div className="mt-10 rounded-2xl border border-black/7 bg-white p-5"><strong className="block text-xs text-[var(--foreground)]">تمرین این هفته</strong><p className="mt-2 text-xs leading-7">یکی از پروژه‌های نیمه‌کاره را باز کن و فقط با حذف سه صدای غیرضروری، فضای بیشتری برای عنصر اصلی بساز.</p></div></div></article></div>; }
